language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - dennys.landy@hotmail.com
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=dlandyr-github -Dsonar.login=$APAW
